import './globals.css'

export const metadata = {
  title: 'Spanish with Josefina',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gray-100'>
        {children}
      </body>
    </html>
  )
}
